CC = g++ 
DEBUG = -g
OPT = -O2 #优化
LIBRARY= -lpthread
FILE = webserver

all:
	${CC} main.cc   -Wall -std=c++11 -o ${FILE} ${DEBUG} ${LIBRARY}

	#${CC} testthreadPool.cpp   -Wall -std=c++11 -o pool ${DEBUG} ${LIBRARY}
